export const siteConfig = {
  name: "Ikram Habib Allah - Computer and network engineer",
  authorName: "Ikram Habib Allah",
  username: "Ikram HA",
  description:
    "Ikram Habib Allah - I am Computer and network engineer with a MIAGE specialization, full-stack developer, software development and AI. Welcome to my portfolio where I showcase my skills, projects, and experiences in the tech world.",
  url: "https://ikram-habib-allah.vercel.app",
  links: {
    github: "https://github.com/ikram77-up",
    templateRepo: "",
  },
  ogImage: "@public/ogImage.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Ikram Habib Allah",
    "Computer and network engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
}
